a=int(input('Enter Number of students in A class :'))
b=int(input('Enter Number of students in B class :'))
c=int(input('Enter Number of students in C class :'))
deskA=(a//2) + (a%2)
deskB=(b//2) + (b%2)
deskC=(c//2) + (c%2)
print('total no of desk :',deskA+deskB+deskC)
